version: "3"
services:
  redis:
    image: redis:3.2.12-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass foobared
    volumes:
      - redis-data:/data

  volumes:
    redis-data:
    driver: local